services:
  - type: web
    name: license-server
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app"
    plan: free
    disks:
      - name: data-license-server
        mountPath: /app/data
        sizeGB: 1
