services:
  - type: web
    name: license-server
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app"
    plan: free
    # PostgreSQL Database sẽ được liên kết tự động qua biến môi trường
    # nên không cần cấu hình disk nữa.